# AfroAuction Configuration File

# Cooldown between auctions for a single player (in seconds)
auction-cooldown: 60

# Maximum number of active auctions a player can have
max-active-auctions: 5

# Minimum and maximum starting price for auctions
min-start-price: 1.0
max-start-price: 1000000.0

# Minimum and maximum duration for auctions (in seconds)
min-auction-duration: 30
max-auction-duration: 86400

# Minimum bid increment as a percentage of the current highest bid
min-bid-percentage-increment: 10

# Item type for the bid button in the GUI (use Material names, e.g., EMERALD, DIAMOND)
bid-button-item: EMERALD

# Hologram settings
hologram-base-height: 1.0
hologram-line-spacing: 0.25
hologram-item-offset: 0.0
hologram-update-interval: 20

# Custom currency symbol to use throughout the plugin
currency-symbol: "$"