auction-cooldown: 60
max-active-auctions: 5
min-start-price: 1.0
max-start-price: 1000000.0
min-auction-duration: 30
max-auction-duration: 86400
min-bid-increment: 1.0

messages:
  player-only: "&cThis command can only be used by players!"
  invalid-usage: "&cInvalid usage! Use /pa <create|bid|notifications|claim> [args]"
  cooldown: "&cYou must wait %cooldown% seconds before creating another auction!"
  max-auctions: "&cYou have reached the maximum number of active auctions (%max_auctions%)!"
  invalid-price-format: "&cInvalid price format! Please enter a valid number."
  invalid-price: "&cPrice must be between %min_price% and %max_price%!"
  invalid-duration-format: "&cInvalid duration format! Use a format like 1d2h3m4s."
  invalid-duration: "&cDuration must be between %min_duration% and %max_duration% seconds!"
  no-item: "&cYou must be holding an item to create an auction!"
  not-chest: "&cYou must be looking at a chest to create an auction!"
  chest-in-use: "&cThis chest is already in use by another auction!"
  auction-created: "&aAuction created for %item% with a starting price of %price% for %duration%!"
  bid-too-low: "&cYour bid must be higher than the current highest bid of %current_bid%!"
  bid-increment-too-low: "&cYour bid must be at least %min_increment% higher than the current bid!"
  insufficient-funds: "&cYou don't have enough money to place this bid!"
  bid-placed: "&aYou have placed a bid of %amount% on %item%!"
  auction-ended: "&cThis auction has already ended!"
  auction-no-bids: "&eYour auction for %item% ended with no bids. The item has been added to your pending items."
  auction-won: "&aYou won the auction for %item% for %amount%!"
  auction-sold: "&aYour auction for %item% sold for %amount%!"
  outbid: "&eYou have been outbid on %item%!"
  no-pending-items: "&cYou have no pending items to claim!"
  claim-success: "&aSuccessfully claimed %item%!"
  inventory-full: "&cYour inventory is full! Please make space to claim your item."
  pending-item-received: "&aYou have received a pending item: %item%!"
  notifications-toggled: "&aNotifications %state%!"
  invalid-bid-format: "&cInvalid bid format! Use !bid <amount>"
  no-auction-target: "&cNo auction found at your target location!"
  gui-bid-item: "&eBid: %amount%"
  gui-time-left: "&eTime Left: %time%"