name: AfroAuction
version: 1.0-SNAPSHOT
main: me.afroninja.afroauction.AfroAuction
api-version: 1.20
depend: [Vault]

commands:
  pa:
    description: Manage auctions (create, bid)
    usage: /<command> <create|bid> [args]
    permission: afroauction.use

permissions:
  afroauction.use:
    description: Allows using auction commands
    default: true