name: AfroAuction
version: 1.0-SNAPSHOT
main: me.afroninja.afroauction.AfroAuction
api-version: 1.20
depend: [Vault]
commands:
  playerauction:
    description: Main command for AfroAuction plugin
    usage: /<command> <subcommand> [args]
    aliases: [pa]