name: AfroAuction
version: 1.0-SNAPSHOT
main: me.afroninja.afroauction.AfroAuction
api-version: 1.20
depend: [Vault]

commands:
  pa:
    description: Manage auctions (create, bid, notifications, claim, view active auctions)
    usage: /<command> <create|notifications|claim|activeauctions> [args]
    permission: afroauction.use
    aliases: [playerauction]

permissions:
  afroauction.use:
    description: Allows using auction commands
    default: true